INSERT INTO category (name) VALUES ('pen');
INSERT INTO category (name) VALUES ('pencil');
INSERT INTO category (name) VALUES ('box');
INSERT INTO category (name) VALUES ('necklace');
INSERT INTO category (name) VALUES ('mug');
INSERT INTO category (name) VALUES ('ring');
INSERT INTO category (name) VALUES ('pencil case');
INSERT INTO category (name) VALUES ('scarf');
INSERT INTO category (name) VALUES ('wallet');
INSERT INTO category (name) VALUES ('purse');
INSERT INTO category (name) VALUES ('pillow');
INSERT INTO category (name) VALUES ('pixel');
INSERT INTO category (name) VALUES ('key case');
INSERT INTO category (name) VALUES ('coat');
INSERT INTO category (name) VALUES ('toy');
INSERT INTO category (name) VALUES ('bracelate');
INSERT INTO category (name) VALUES ('bag');
INSERT INTO category (name) VALUES ('candle');
INSERT INTO category (name) VALUES ('frame');
INSERT INTO category (name) VALUES ('vase');

