CREATE TABLE user(UID INT NOT NULL,email varchar(50) NOT NULL,last_name nvarchar(50) NOT NULL,first_name nvarchar(50) NOT NULL,phone char(11) NOT NULL,address nvarchar(100) NOT NULL,password char(10) NOT NULL,PRIMARY KEY (UID));

CREATE TABLE request(RID INT NOT NULL,UID INT NOT NULL,text nvarchar(50) NOT NULL,PRIMARY KEY (RID),CONSTRAINT fk_request_user FOREIGN KEY (UID) REFERENCES user(UID));

CREATE TABLE basket(BID INT NOT NULL,UID INT NOT NULL ,PRIMARY KEY (BID),CONSTRAINT fk_basket_user FOREIGN KEY (UID) REFERENCES user(UID));

CREATE TABLE store(SID INT NOT NULL,name nvarchar(10),PRIMARY KEY (SID));

CREATE TABLE discount(DID INT NOT NULL,percentage float,PRIMARY KEY (DID));

CREATE TABLE category(CAID INT NOT NULL,name nvarchar(50),PRIMARY KEY (CAID));
 
CREATE TABLE product(PRID INT NOT NULL,name nvarchar(50),cost float NOT NULL,color varchar(50) NOT NULL,size varchar(50) NOT NULL,isAvailable bit NOT NULL,count INT NOT NULL,SID INT NOT NULL,CONSTRAINT fk_store FOREIGN KEY (SID) REFERENCES store(SID),CAID INT NOT NULL,CONSTRAINT fk_category FOREIGN KEY (CAID) REFERENCES category(CAID),DID INT NULL,CONSTRAINT fk_discount FOREIGN KEY (DID) REFERENCES discount(DID),PRIMARY KEY (PRID));

CREATE TABLE deliverer(DEID INT NOT NULL,name nvarchar(50) NOT NULL,phone char(11) NOT NULL,PRIMARY KEY (DEID));

CREATE TABLE purchase(PUID INT NOT NULL,date date NOT NULL,type bit NOT NULL,phone char(11) NULL,last_name nvarchar(50) NULL,first_name nvarchar(50) NULL,address nvarchar(100) NULL,BID INT NOT NULL,CONSTRAINT fk_basket FOREIGN KEY (BID) REFERENCES basket(BID),DEID INT NULL,CONSTRAINT fk_deliverer FOREIGN KEY (DEID) REFERENCES deliverer(DEID),PRIMARY KEY (PUID));

CREATE TABLE comment(COID INT NOT NULL,text nvarchar(50) NOT NULL,date date NOT NULL,PRID INT NOT NULL,CONSTRAINT fk_product_comment FOREIGN KEY (PRID) REFERENCES product(PRID),UID INT NOT NULL,CONSTRAINT fk_user_comment FOREIGN KEY (UID) REFERENCES user(UID),PRIMARY KEY (COID));

CREATE TABLE basket_product(BID INT NOT NULL,CONSTRAINT fk_bp_basket FOREIGN KEY (BID) REFERENCES basket(BID),PRID INT NOT NULL,CONSTRAINT fk_bp_product FOREIGN KEY (PRID) REFERENCES product(PRID),Count INT DEFAULT 1, PRIMARY KEY (BID,PRID));

					   
					 
	
