INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('flower pen',2.9,'s','pink',20,1,1,1);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('bik pencil',3.9,'s','blue',5,2,1,2);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('love box',2.8,'m','red',0,3,1,3);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('golden necklace',20,'s','gold',7,4,1,4);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('magic mug',25,'l','black',9,5,1,5);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('heart ring',20,'l','silver',4,6,1,6);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('angry bird pencil case',20.5,'m','green',11,7,1,7);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('butterfly scarf',7.9,'s','blue',6,8,1,8);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('new wallet',30,'l','brown',2,9,1,9);
INSERT INTO product (name,cost,size,color,count,SID,CAID,DID) VALUES ('purse',35,'s','cream',8,10,1,10);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('soft pillow',5.4,'l','white',15,11,1,11);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('computer science pixel',5.8,'l','black',3,1,12);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('skull key case',2.8,'l','black',0,1,13);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('felt coat',70.2,'m','purple',2,1,14);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('doll',9.5,'s','pink',3,1,15);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('golden bracelate',20,'m','gold',3,1,16);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('floral bag',7.9,'s','green',2,1,17);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('diamond candle',2.8,'s','white',1,1,18);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('wooden frame',5,'m','brown',7,1,19);
INSERT INTO product (name,cost,size,color,count,SID,CAID) VALUES ('fantasy vase',2.8,'m','cyan',2,2,20);

