INSERT INTO request(text,UID) VALUES ("tashakkor",11);
INSERT INTO request(text,UID) VALUES ("lotfan paskhgoo bashid",14);
INSERT INTO request(text,UID) VALUES ("jamedadi ham biavarid",18);
INSERT INTO request(text,UID) VALUES ("moshtari madari che shod?",5);
INSERT INTO request(text,UID) VALUES ("adab mard beh az dolate oost",1);
INSERT INTO request(text,UID) VALUES ("omid bazr hoviate mast",8);
INSERT INTO request(text,UID) VALUES ("mohsoolat motenave tari biavarid",14);
INSERT INTO request(text,UID) VALUES ("lebase tabestani nmiavarid?",10);
INSERT INTO request(text,UID) VALUES ("gheimate mahsool ba keifiat on mtenaseb nist",5);
INSERT INTO request(text,UID) VALUES ("kasi nist???",3);
INSERT INTO request(text,UID) VALUES ("be darkhast ha pasokh dahid",15);
INSERT INTO request(text,UID) VALUES ("faseleye beyne sefaresh va tahvil ra kam konid",1);
INSERT INTO request(text,UID) VALUES ("dastbande e tarhe almas tamam shode",20);
INSERT INTO request(text,UID) VALUES ("tashakkore faravaan",11);
INSERT INTO request(text,UID) VALUES ("maliat bar arzeshe afzoode ra hazf konid",7);
INSERT INTO request(text,UID) VALUES ("hamishe hagh ba moshtarie",5);
INSERT INTO request(text,UID) VALUES (" chera pasokh gu nistid ?",12);
INSERT INTO request(text,UID) VALUES (" keyiate kala ha monaseb nis",2);
INSERT INTO request(text,UID) VALUES (" brand haye motenave tari ra pushesh dahid",14);
INSERT INTO request(text,UID) VALUES ("ba tashkor az zahamate shoma",1);
INSERT INTO request(text,UID) VALUES ("sgheymat ha bala mibashand",14);
