INSERT INTO request(RID,text,UID) VALUES (0,"tashakkor",11);
INSERT INTO request(RID,text,UID) VALUES (1,"lotfan paskhgoo bashid",14);
INSERT INTO request(RID,text,UID) VALUES (2,"jamedadi ham biavarid",18);
INSERT INTO request(RID,text,UID) VALUES (3,"moshtari madari che shod?",5);
INSERT INTO request(RID,text,UID) VALUES (4,"adab mard beh az dolate oost",1);
INSERT INTO request(RID,text,UID) VALUES (5,"omid bazr hoviate mast",8);
INSERT INTO request(RID,text,UID) VALUES (6,"mohsoolat motenave tari biavarid",14);
INSERT INTO request(RID,text,UID) VALUES (7,"lebase tabestani nmiavarid?",10);
INSERT INTO request(RID,text,UID) VALUES (8,"gheimate mahsool ba keifiat on mtenaseb nist",5);
INSERT INTO request(RID,text,UID) VALUES (9,"kasi nist???",3);
INSERT INTO request(RID,text,UID) VALUES (10,"be darkhast ha pasokh dahid",15);
INSERT INTO request(RID,text,UID) VALUES (11,"faseleye beyne sefaresh va tahvil ra kam konid",1);
INSERT INTO request(RID,text,UID) VALUES (12,"dastbande e tarhe almas tamam shode",20);
INSERT INTO request(RID,text,UID) VALUES (13,"tashakkore faravaan",11);
INSERT INTO request(RID,text,UID) VALUES (14,"maliat bar arzeshe afzoode ra hazf konid",7);
INSERT INTO request(RID,text,UID) VALUES (15,"hamishe hagh ba moshtarie",5);
INSERT INTO request(RID,text,UID) VALUES (16," chera pasokh gu nistid ?",12);
INSERT INTO request(RID,text,UID) VALUES (17," keyiate kala ha monaseb nis",2);
INSERT INTO request(RID,text,UID) VALUES (18," brand haye motenave tari ra pushesh dahid",14);
INSERT INTO request(RID,text,UID) VALUES (19,"ba tashkor az zahamate shoma",1);
INSERT INTO request(RID,text,UID) VALUES (20,"sgheymat ha bala mibashand",14);
