INSERT INTO store (name) VALUES ('Sirencester');
INSERT INTO store (name) VALUES ('Cappadocia');
INSERT INTO store (name) VALUES ('Transmere');
INSERT INTO store (name) VALUES ('Willesden');
INSERT INTO store (name) VALUES ('Greenflower');
INSERT INTO store (name) VALUES ('Romsey');
INSERT INTO store (name) VALUES ('Ormskirk');
INSERT INTO store (name) VALUES ('Pendle');
INSERT INTO store (name) VALUES ('Penzance');
INSERT INTO store (name) VALUES ('Caelkirk');
INSERT INTO store (name) VALUES ('Fanfoss');
INSERT INTO store (name) VALUES ('Sherfield');
INSERT INTO store (name) VALUES ('Azmarin');
INSERT INTO store (name) VALUES ('Hartlepool');
INSERT INTO store (name) VALUES ('Hankala');
INSERT INTO store (name) VALUES ('Bredon');
INSERT INTO store (name) VALUES ('Drumnadrochit');
INSERT INTO store (name) VALUES ('Tergaron');
INSERT INTO store (name) VALUES ('Grimsby');
INSERT INTO store (name) VALUES ('Aquarin ');

